/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An object indicating whether to enable storage for the APIs included. An explicit true or false value will override an existing setting. If an API is not specified, its settings will be left as is.
 */
export interface StorageStatusRequest {
  /**
   * Optional. Indicates whether to enable storage for the Vehicle API.
   */
  vehicle?: boolean;
  /**
   * Optional. Indicates whether to enable storage for the Transport API.
   */
  transport?: boolean;
  [k: string]: unknown;
}
