/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The hook to create
 */
export interface CreateHookRequest {
  /**
   * The URL of the hook.
   */
  hookUrl: string;
  /**
   * The list of APIs to subscribe to. Valid values are: `'vehicle'`, `'transport'`.
   */
  apis: unknown[];
  [k: string]: unknown;
}
