/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The hook to create
 */
export interface CreateHookRequest {
  /**
   * The URL of the hook.
   */
  hookUrl: string;
  /**
   * An object with properties that correspond to API subscriptions.
   */
  apis: {
    /**
     * Optional. Indicates whether to enable storage for the Vehicle API.
     */
    vehicle?: boolean;
    /**
     * Optional. Indicates whether to enable storage for the Transport API.
     */
    transport?: boolean;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
