/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Response object returned by the Vehicle API on successful execution.
 */
export interface VehicleAPIResponse {
  /**
   * Includes the names of the recognition engines that successfully processed the request. (*Removed since version 1.3.*)
   */
  "*engines"?: string[];
  /**
   * The name of the node this request has been processed by. This is diagnostic information to be included in error reports.
   */
  nodename?: string;
  /**
   * Total processing time spent on the worker node (includes processing, image loading and latency). (*Available since version 1.4.*)
   */
  nodetime?: number;
  /**
   * Startup time of the node processing the request. This can be greater in case of a cold start. (*Available since version 1.4.*)
   */
  startuptime?: number;
  /**
   * Net processing time spent on recognizing the already loaded image. Use this number if you want to make an objective comparison between the difficulty of different images. (*Available since version 1.4*)
   */
  recognitiontime?: number;
  /**
   * The version of the API that returned the response. Incremented each time the response structure changes.
   */
  version?: string;
  /**
   * The recognition results.
   */
  data?: {
    /**
     * The recognition results returned by each recognition service specified for the vehicles detected in the image (**plate** for *anpr*, **mmr** for *mmr*, and **markings** for *adr* service).
     */
    vehicles?: {
      /**
       * The bounds of the vehicle. (*Available since version 1.3.*)
       */
      bounds?: {
        /**
         * The coordinates of the license plate extension, on the basis of which the vehicle type can be determined.
         */
        extendedPlateFrame?: {
          /**
           * The bottom left corner of the rectangle.
           */
          bottomLeft?: {
            /**
             * x coordinate
             */
            x?: number;
            /**
             * y coordinate
             */
            y?: number;
            [k: string]: unknown;
          };
          /**
           * The bottom right corner of the rectangle.
           */
          bottomRight?: {
            /**
             * x coordinate
             */
            x?: number;
            /**
             * y coordinate
             */
            y?: number;
            [k: string]: unknown;
          };
          /**
           * The top left corner of the rectangle.
           */
          topLeft?: {
            /**
             * x coordinate
             */
            x?: number;
            /**
             * y coordinate
             */
            y?: number;
            [k: string]: unknown;
          };
          /**
           * The top right corner of the rectangle.
           */
          topRight?: {
            /**
             * x coordinate
             */
            x?: number;
            /**
             * y coordinate
             */
            y?: number;
            [k: string]: unknown;
          };
          [k: string]: unknown;
        };
        /**
         * The coordinates of the vehicle if provided by the MMR engine.
         */
        vehicleFrame?: {
          /**
           * The bottom left corner of the rectangle.
           */
          bottomLeft?: {
            /**
             * x coordinate
             */
            x?: number;
            /**
             * y coordinate
             */
            y?: number;
            [k: string]: unknown;
          };
          /**
           * The bottom right corner of the rectangle.
           */
          bottomRight?: {
            /**
             * x coordinate
             */
            x?: number;
            /**
             * y coordinate
             */
            y?: number;
            [k: string]: unknown;
          };
          /**
           * The top left corner of the rectangle.
           */
          topLeft?: {
            /**
             * x coordinate
             */
            x?: number;
            /**
             * y coordinate
             */
            y?: number;
            [k: string]: unknown;
          };
          /**
           * The top right corner of the rectangle.
           */
          topRight?: {
            /**
             * x coordinate
             */
            x?: number;
            /**
             * y coordinate
             */
            y?: number;
            [k: string]: unknown;
          };
          [k: string]: unknown;
        };
        [k: string]: unknown;
      };
      /**
       * The make, model and color of the vehicle.
       */
      mmr?: {
        /**
         * True if an MMR engine found mmr information in the image, otherwise false. (*Available since version 1.2.*)
         */
        found?: boolean;
        /**
         * The name of the MMR engine that successfully processed this vehicle. (*Available since version 1.3.*)
         */
        engine?: string;
        /**
         * The vehicle’s category.
         */
        category?: string;
        /**
         * The confidence level of the vehicle category recognition.
         */
        categoryConfidence?: number;
        /**
         * **DEPRECATED:** The vehicle’s view (frontal or rear). (*Available since version 1.2.*)
         */
        heading?: string;
        /**
         * **DEPRECATED:** The confidence level of the view recognition. (*Available since version 1.2.*)
         */
        headingConfidence?: number;
        /**
         * The vehicle’s color.
         */
        color?: {
          /**
           * the blue component of the color
           */
          b?: number;
          /**
           * the green component of the color
           */
          g?: number;
          /**
           * the red component of the color
           */
          r?: number;
          [k: string]: unknown;
        };
        /**
         * The confidence level of the vehicle color recognition.
         */
        colorConfidence?: number;
        /**
         * The vehicle’s color as a string. The value is 'GRAYSCALE' for grayscale input images.
         */
        colorName?: string;
        /**
         * The make/brand of the vehicle.
         */
        make?: string;
        /**
         * The confidence level of  vehicle make recognition. (*Available since version 1.2.*)
         */
        makeConfidence?: number;
        /**
         * The model type of a vehicle.
         */
        model?: string;
        /**
         * The confidence level of the vehicle model recognition. (*Available since version 1.2.*)
         */
        modelConfidence?: number;
        /**
         * The confidence level of the vehicle make and model recognition. (*Removed since version 1.2.*)
         */
        "*makeAndModelConfidence"?: number;
        /**
         * The submodel type of a vehicle. (*Removed since version 1.2.*)
         */
        "*submodel"?: string;
        /**
         * The running time of the engine in milliseconds.
         */
        proctime?: number;
        /**
         * The body type of the vehicle. E.g. 'sedan', 'SUV', 'hatchback', etc. (*Available since version 1.4.*)
         */
        bodyType?: string;
        /**
         * The confidence level of the body type recognition. (*Available since version 1.4.*)
         */
        bodyTypeConfidence?: number;
        /**
         * The orientation of the vehicle in the image. Available values: `rear`, `front`, `rear_side`, `front_side`, `side`. (*Available since version 1.4.*)
         */
        viewPoint?: string;
        /**
         * The confidence level of the view point recognition. (*Available since version 1.4.*)
         */
        viewPointConfidence?: number;
        /**
         * A list of hints that help improve recognition accuracy. (*Available since version 1.4.*)
         */
        imageTooltips?: [] | [string];
        /**
         * A list of hints that help improve recognition accuracy. (*Available since version 1.4.*)
         */
        frameTooltips?: [] | [string];
        [k: string]: unknown;
      };
      /**
       * The recognized license plate.
       */
      plate?: {
        /**
         * True if an ANPR engine found plate information in the image, otherwise false. (*Available since version 1.2.*)
         */
        found?: boolean;
        /**
         * The name of the ANPR engine that successfully processed this vehicle. (*Available since version 1.3.*)
         */
        engine?: string;
        /**
         * Indicates whether the license plate has a dark background color. Only returned if the engine does not support color analysis. (*Available since version 1.4.*)
         */
        bgDark?: boolean;
        /**
         * The color of the license plate background if provided by the ANPR engine, can be white or black. This also means that the engine does not give yellow to taxis and green to electric cars, but white. The color is specified by an RGB (red-green-blue) code which properties (r, g, and b respectively) are integer numbers between 0 and 255.
         */
        bgColor?: {
          /**
           * the blue component of the color
           */
          b?: number;
          /**
           * the green component of the color
           */
          g?: number;
          /**
           * the red component of the color
           */
          r?: number;
          [k: string]: unknown;
        };
        /**
         * The dedicated area color if provided by the ANPR engine. (*Available since version 1.2.*)
         */
        daColor?: {
          /**
           * the blue component of the color
           */
          b?: number;
          /**
           * the green component of the color
           */
          g?: number;
          /**
           * the red component of the color
           */
          r?: number;
          [k: string]: unknown;
        };
        /**
         * The color of the license plate foreground if provided by the ANPR engine.
         */
        color?: {
          /**
           * the blue component of the color
           */
          b?: number;
          /**
           * the green component of the color
           */
          g?: number;
          /**
           * the red component of the color
           */
          r?: number;
          [k: string]: unknown;
        };
        /**
         * The estimated height (in millimeters) of the license plate. (*Available since version 1.4.*)
         */
        plateHeight?: number;
        /**
         * The estimated width (in millimeters) of the license plate. (*Available since version 1.4.*)
         */
        plateWidth?: number;
        /**
         * Overall confidence of the license plate calculated from plate type, position, and character confidence values (plateTypeConfidence * positionConfidence * average of characterConfidences). If you need more fine-grained confidence data, use the other plate or character-level confidence properties.
         */
        confidence?: number;
        /**
         * Confidence of license plate text recognition. (*Available since version 1.4.*)
         */
        textConfidence?: number;
        /**
         * Combined confidence of licese plate text, country, and state recognition. (*Available since version 1.4.*)
         */
        normalizedConfidence?: number;
        /**
         * Confidence of the license plate type. (*Available since version 1.1.*)
         */
        plateTypeConfidence?: number;
        /**
         * Confidence of the license plate position. (*Available since version 1.1.*)
         */
        positionConfidence?: number;
        /**
         * The running time of the engine in milliseconds.
         */
        proctime?: number;
        /**
         * The category of the license plate. (*Available since version 1.1.*) For the list of possible values please refer to the [Carmen ANPR Reference Manual](https://adaptiverecognition.com/app/uploads/DOC/Software/Carmen/ANPR/carmen_anpr_reference_manual.pdf)
         */
        category?: string;
        /**
         * The nationality of the license plate. For a list of possible values please refer to [this table](/docs/content/references/countries).
         */
        country?: string;
        /**
         * Where it makes sense, the code of the state, county or region.
         */
        state?: string;
        /**
         * The Adaptive Recognition type code of the table. For a list of possible values please refer to the [Carmen ANPR Reference Manual](https://adaptiverecognition.com/app/uploads/DOC/Software/Carmen/ANPR/carmen_anpr_reference_manual.pdf).
         */
        plateType?: number;
        /**
         * If present, indicates whether the plate size has been determined based on the plate type (`database`) or using a statistical estimation (`statistical`). If a plate size has not been returned, this property is missing.
         */
        plateSizeSource?: string;
        /**
         * The recognized text of the license plate with gap symbols as it is visible on the plate (<b>*</b> for crest, **¶** for new row, **space** for space, **|** for vertical line, **-** for hyphen, and **(** **)** for begin end symbol of small characters. *Available since version 1.3.*)
         */
        separatedText?: string;
        /**
         * The recognized text of the license plate.
         */
        unicodeText?: string;
        /**
         * The coordinates of the license plate found.
         */
        plateROI?: {
          /**
           * The bottom left corner of the rectangle.
           */
          bottomLeft?: {
            /**
             * x coordinate
             */
            x?: number;
            /**
             * y coordinate
             */
            y?: number;
            [k: string]: unknown;
          };
          /**
           * The bottom right corner of the rectangle.
           */
          bottomRight?: {
            /**
             * x coordinate
             */
            x?: number;
            /**
             * y coordinate
             */
            y?: number;
            [k: string]: unknown;
          };
          /**
           * The top left corner of the rectangle.
           */
          topLeft?: {
            /**
             * x coordinate
             */
            x?: number;
            /**
             * y coordinate
             */
            y?: number;
            [k: string]: unknown;
          };
          /**
           * The top right corner of the rectangle.
           */
          topRight?: {
            /**
             * x coordinate
             */
            x?: number;
            /**
             * y coordinate
             */
            y?: number;
            [k: string]: unknown;
          };
          [k: string]: unknown;
        };
        /**
         * An array of read characters, including character structures.
         */
        plateChars?: {
          /**
           * The numeric code of the character.
           */
          code?: number;
          /**
           * Indicates whether the character has a dark background color. Only returned if the engine does not support color analysis. (*Available since version 1.4.*)
           */
          bgDark?: boolean;
          /**
           * The background color of the character.
           */
          bgColor?: {
            /**
             * the blue component of the color
             */
            b?: number;
            /**
             * the green component of the color
             */
            g?: number;
            /**
             * the red component of the color
             */
            r?: number;
            [k: string]: unknown;
          };
          /**
           * The color of the character.
           */
          color?: {
            /**
             * the blue component of the color
             */
            b?: number;
            /**
             * the green component of the color
             */
            g?: number;
            /**
             * the red component of the color
             */
            r?: number;
            [k: string]: unknown;
          };
          /**
           * The engine's confidence for the character.
           */
          confidence?: number;
          /**
           * The coordinates of the given character.
           */
          charROI?: {
            /**
             * The bottom left corner of the rectangle.
             */
            bottomLeft?: {
              /**
               * x coordinate
               */
              x?: number;
              /**
               * y coordinate
               */
              y?: number;
              [k: string]: unknown;
            };
            /**
             * The bottom right corner of the rectangle.
             */
            bottomRight?: {
              /**
               * x coordinate
               */
              x?: number;
              /**
               * y coordinate
               */
              y?: number;
              [k: string]: unknown;
            };
            /**
             * The top left corner of the rectangle.
             */
            topLeft?: {
              /**
               * x coordinate
               */
              x?: number;
              /**
               * y coordinate
               */
              y?: number;
              [k: string]: unknown;
            };
            /**
             * The top right corner of the rectangle.
             */
            topRight?: {
              /**
               * x coordinate
               */
              x?: number;
              /**
               * y coordinate
               */
              y?: number;
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
          [k: string]: unknown;
        }[];
        [k: string]: unknown;
      };
      /**
       * The markings found on the vehicle. (*Available since version 1.3.*)
       */
      markings?: {
        /**
         * The name of the ANPR engine that successfully processed this marking.
         */
        engine?: string;
        /**
         * Overall confidence of the plate.
         */
        confidence?: number;
        /**
         * Confidence of the plate type. (*Not provided for eADR and A plates*)
         */
        plateTypeConfidence?: number;
        /**
         * Confidence of the plate position. (*Not provided for eADR and A plates*)
         */
        positionConfidence?: number;
        /**
         * The running time of the engine in milliseconds.
         */
        proctime?: number;
        /**
         * The Adaptive Recognition type code of the table. For a list of possible values please refer to the [Carmen ANPR Reference Manual](https://adaptiverecognition.com/app/uploads/DOC/Software/Carmen/ANPR/carmen_anpr_reference_manual.pdf).
         */
        plateType?: number;
        /**
         * The type of the table. **ADR** for ADR plates, **E** for empty ADR plates, **AP** for A plates, and **IMO** for IMO plates
         */
        type?: string;
        /**
         * The recognized text of the ADR plate or a textual representation of the IMO plate.
         */
        unicodeText?: string;
        /**
         * The coordinates of the plate found.
         */
        plateROI?: {
          /**
           * The bottom left corner of the rectangle.
           */
          bottomLeft?: {
            /**
             * x coordinate
             */
            x?: number;
            /**
             * y coordinate
             */
            y?: number;
            [k: string]: unknown;
          };
          /**
           * The bottom right corner of the rectangle.
           */
          bottomRight?: {
            /**
             * x coordinate
             */
            x?: number;
            /**
             * y coordinate
             */
            y?: number;
            [k: string]: unknown;
          };
          /**
           * The top left corner of the rectangle.
           */
          topLeft?: {
            /**
             * x coordinate
             */
            x?: number;
            /**
             * y coordinate
             */
            y?: number;
            [k: string]: unknown;
          };
          /**
           * The top right corner of the rectangle.
           */
          topRight?: {
            /**
             * x coordinate
             */
            x?: number;
            /**
             * y coordinate
             */
            y?: number;
            [k: string]: unknown;
          };
          [k: string]: unknown;
        };
        /**
         * An array of read characters, including character structures. (*Not provided for IMO, eADR and A plates*)
         */
        plateChars?: {
          /**
           * The numeric code of the character.
           */
          code?: number;
          /**
           * The background color of the character.
           */
          bgColor?: {
            /**
             * the blue component of the color
             */
            b?: number;
            /**
             * the green component of the color
             */
            g?: number;
            /**
             * the red component of the color
             */
            r?: number;
            [k: string]: unknown;
          };
          /**
           * The color of the character.
           */
          color?: {
            /**
             * the blue component of the color
             */
            b?: number;
            /**
             * the green component of the color
             */
            g?: number;
            /**
             * the red component of the color
             */
            r?: number;
            [k: string]: unknown;
          };
          /**
           * The engine's confidence for the character.
           */
          confidence?: number;
          /**
           * The coordinates of the given character.
           */
          charROI?: {
            /**
             * The bottom left corner of the rectangle.
             */
            bottomLeft?: {
              /**
               * x coordinate
               */
              x?: number;
              /**
               * y coordinate
               */
              y?: number;
              [k: string]: unknown;
            };
            /**
             * The bottom right corner of the rectangle.
             */
            bottomRight?: {
              /**
               * x coordinate
               */
              x?: number;
              /**
               * y coordinate
               */
              y?: number;
              [k: string]: unknown;
            };
            /**
             * The top left corner of the rectangle.
             */
            topLeft?: {
              /**
               * x coordinate
               */
              x?: number;
              /**
               * y coordinate
               */
              y?: number;
              [k: string]: unknown;
            };
            /**
             * The top right corner of the rectangle.
             */
            topRight?: {
              /**
               * x coordinate
               */
              x?: number;
              /**
               * y coordinate
               */
              y?: number;
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
          [k: string]: unknown;
        }[];
        [k: string]: unknown;
      }[];
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
