/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The unique identifier of the API.
 */
export type APIID = string;
/**
 * The friendly identifier of the API. E.g.: `vehicle`.
 */
export type FriendlyAPIID = string;
/**
 * Friendly identifier of the API stage.
 */
export type StageName = string;
/**
 * Indicates whether this stage serves the upcoming, beta quality version of the API.
 */
export type Beta = boolean;
/**
 * For internal use only.
 */
export type AuthenticationTokenRequired = string;
/**
 * For internal use only.
 */
export type Enabled = boolean;
/**
 * An array of objects listing the properties of API stages.
 */
export type APIStages = APIStage[];

/**
 * Represents an API stage.
 */
export interface APIStage {
  id: APIID;
  api: FriendlyAPIID;
  stage: StageName;
  swagger: APIStageSwaggerDefinition;
  beta: Beta;
  authTokenRequired: AuthenticationTokenRequired;
  enabled: Enabled;
  [k: string]: unknown;
}
/**
 * The Swagger definition of the API stage. Only included if the query parameter `detailed` is `true`.
 */
export interface APIStageSwaggerDefinition {
  [k: string]: unknown;
}
