/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The unique identifier of the dimension.
 */
export type DimensionID = string;
/**
 * The display name of the dimension.
 */
export type DimensionName = string;
/**
 * The number of API requests included in the dimension.
 */
export type RequestCount = number;
/**
 * An array of available subscription dimensions.
 */
export type Dimensions = {
  id: DimensionID;
  name: DimensionName;
  requestCount: RequestCount;
  [k: string]: unknown;
}[];
