/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The ID of the usage plan that applies to this subscription.
 */
export type UsagePlanID = string;
/**
 * The friendly identifier of the dimension of this subscription.
 */
export type Dimension = string;
/**
 * A millisecond timestamp indicating when the subscription started.
 */
export type StartTime = number;
/**
 * A millisecond timestamp indicating the next turnover date of the subscription.
 */
export type EndTime = number;
/**
 * `stripe` or `marketplace`, indicates whether this subscription has been initiated via the Stripe payment provider or via AWS Marketplace
 */
export type SubscriptionType = "stripe" | "marketplace";
/**
 * The product this subscription belongs to.
 */
export type ProductID = string;
/**
 * An array of paid subscriptions.
 */
export type PaidSubscriptions = PaidSubscription[];

/**
 * Information about a paid subscription the authenticated user has.
 */
export interface PaidSubscription {
  id: UsagePlanID;
  dimension: Dimension;
  startTime: StartTime;
  endTime: EndTime;
  type: SubscriptionType;
  productId?: ProductID;
  [k: string]: unknown;
}
