/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The start of the time interval queried as a millisecond timestamp, not older than 90 days.
 */
export type StartTime = string;
/**
 * The end of the time interval queried as a millisecond timestamp.
 */
export type EndTime = string;
/**
 * Lists the number of credits used for each day of the interval queried. The sum of this array is the total number of credits used in the interval queried.
 */
export type Usages = number[];

/**
 * Usage data for a paid API subscription.
 */
export interface PaidSubscriptionUsages {
  startTime: StartTime;
  endTime: EndTime;
  usages: Usages;
  [k: string]: unknown;
}
