/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Lists of publicly available pricing tiers by product.
 */
export interface Prices {
  /**
   * This interface was referenced by `Prices`'s JSON-Schema definition
   * via the `patternProperty` "^.*$".
   */
  [k: string]: Price[];
}
/**
 * A pricing tier for a product.
 */
export interface Price {
  /**
   * The number of requests allowed in the interval.
   */
  requestCount: number;
  /**
   * The rate limit for the pricing tier.
   */
  throttle: {
    /**
     * The number of requests allowed per second.
     */
    rateLimit: number;
    /**
     * The number of requests allowed in a burst.
     */
    burstLimit: number;
    [k: string]: unknown;
  };
  /**
   * Whether the pricing tier is free or not.
   */
  free?: boolean;
  /**
   * The dimension of the pricing tier.
   */
  dimension?: string;
  /**
   * The title of the pricing tier.
   */
  title?: string;
  /**
   * The price of the pricing tier.
   */
  price?: number;
  /**
   * The currency of the pricing tier.
   */
  currency?: string;
  /**
   * The interval the pricing tier is billed at.
   */
  interval?: string;
  /**
   * The overuse fee for the pricing tier.
   */
  overuse?: {
    /**
     * The price of the overuse fee.
     */
    price: number;
    /**
     * The currency of the overuse fee.
     */
    currency: string;
  };
  /**
   * The quota that applies to the pricing tier.
   */
  quota?: {
    /**
     * The limit of the quota.
     */
    limit: number;
    /**
     * The number of days or months the quota is offset by.
     */
    offset: number;
    /**
     * The period the quota is measured over.
     */
    period: "DAY" | "MONTH";
  };
}
