/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The unique identifier of this product.
 */
export type ID = string;
/**
 * The human-readable display name of this product.
 */
export type Name = string;
/**
 * The Stripe product code associated with this product.
 */
export type StripeProductCode = string;
/**
 * The Stripe product code used for metering usage for this product.
 */
export type StripeUsagesProductCode = string;
/**
 * The AWS Marketplace product code associated with this product.
 */
export type MarketplaceProductCode = string;
/**
 * An array of products a suer can subscribe to.
 */
export type Products = Product[];

/**
 * Represents a product a user can subscribe to.
 */
export interface Product {
  id: ID;
  name: Name;
  stripeProductCode: StripeProductCode;
  stripeUsagesProductCode: StripeUsagesProductCode;
  marketplaceProductCode: MarketplaceProductCode;
  [k: string]: unknown;
}
