/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The unique identifier of the usage plan.
 */
export type ID = string;
/**
 * The name of the usage plan.
 */
export type Name = string;
/**
 * The description of the usage plan.
 */
export type Description = string;
/**
 * The friendly identifiers of the APIs this usage plan applies to.
 */
export type APIs = string[];
/**
 * The ID of the API.
 */
export type APIID = string;
/**
 * The friendly identifier of the stage.
 */
export type APIStage = string;
/**
 * The maximum number of requests in one period.
 */
export type Limit = number;
/**
 * When the quota window starts inside a calendar period (e.g. if `offset` is 10 and `period` is `MONTH`, counting requests restarts on the 10th of every calendar month).
 */
export type Offset = number;
/**
 * The calendar period the quota applies to.
 */
export type Period = "DAY" | "MONTH";
/**
 * The maximum rate (requests/second).
 */
export type RateLimit = number;
/**
 * The maximum number of concurrent requests.
 */
export type BurstLimit = number;
/**
 * Tor internal use only.
 */
export type AutoSignUp = boolean;
/**
 * The paid subscription dimensions this usage plan applies to.
 */
export type Dimensions = string[];
/**
 * For internal use only.
 */
export type StripeProductCode = string;
/**
 * For internal use only.
 */
export type MarketplaceProductCode = string;
/**
 * For internal use only.
 */
export type Enabled = boolean;
/**
 * Indicates whether this usage plan applies to one or more paid subscription dimenions or the free tier.
 */
export type Paid = boolean;
/**
 * List of Usage Plans.
 */
export type UsagePlans = UsagePlan[];

/**
 * The properties of a Usage Plan.
 */
export interface UsagePlan {
  id: ID;
  name: Name;
  description: Description;
  apis: APIs;
  apiStages: APIStages;
  quota: Quota;
  throttle: Throttle;
  autoSignup: AutoSignUp;
  dimensions: Dimensions;
  stripeProductCode: StripeProductCode;
  marketplaceProductCode: MarketplaceProductCode;
  enabled: Enabled;
  paid: Paid;
  [k: string]: unknown;
}
/**
 * The API stages this usage plan applies to.
 */
export interface APIStages {
  apiId: APIID;
  stage: APIStage;
  [k: string]: unknown;
}
/**
 * The number of requests included in this usage plan.
 */
export interface Quota {
  limit: Limit;
  offset: Offset;
  period: Period;
  [k: string]: unknown;
}
/**
 * Request rate and conncurrency limits that apply for this Usage Plan.
 */
export interface Throttle {
  rateLimit: RateLimit;
  burstLimit: BurstLimit;
  [k: string]: unknown;
}
