name: CI

on: [push, pull_request]

env:
  TEST_DEV_API_KEY: ${{ secrets.API_TEST_EU_API_KEY_DEV }}
  TEST_EU_PROD_API_KEY: ${{ secrets.API_TEST_EU_API_KEY_PROD }}
  TEST_US_PROD_API_KEY: ${{ secrets.API_TEST_US_API_KEY_PROD }}
  TEST_DEV_ENDPOINT_URL: ${{ secrets.TEST_DEV_ENDPOINT_URL }}

jobs:
  install:
    runs-on: ubuntu-latest
    container:
      image: node:16
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ github.sha }}-node-modules
          restore-keys: |
            ${{ github.sha }}-node-modules
            ${{ github.run_id }}-node-modules
            node-modules

      - name: Install dependencies
        run: npm ci

  lint:
    needs: [install]
    runs-on: ubuntu-latest
    container:
      image: node:16
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ github.sha }}-node-modules
          restore-keys: |
            ${{ github.sha }}-node-modules
            ${{ github.run_id }}-node-modules
            node-modules

      - name: Lint
        run: npm run lint

  build:
    needs: [lint]
    runs-on: ubuntu-latest
    container:
      image: node:16
      options: --user root
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ github.sha }}-node-modules
          restore-keys: |
            ${{ github.sha }}-node-modules
            ${{ github.run_id }}-node-modules
            node-modules

      - name: Set permissions
        run: chown -R $USER:$USER .

      - name: Build
        run: |
          chown -R $(whoami) $(pwd)
          npm run build

  test:
    needs: [build]
    runs-on: ubuntu-latest
    container:
      image: node:16
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ github.sha }}-node-modules
          restore-keys: |
            ${{ github.sha }}-node-modules
            ${{ github.run_id }}-node-modules
            node-modules

      - name: Test
        run: |
          npm run test:ci
          mkdir .public
          cp -r coverage/* .public
          mv .public public

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: public
